import { convertToEm } from "./.styles/functions";

/** @type {import('tailwindcss').Config} */
export default {
	content: ["./src/**/*.{html,js,svelte,ts}"],
	theme: {
		screens: {
			600: convertToEm("640px"),
			700: convertToEm("768px"),
			1000: convertToEm("1024px"),
			1200: convertToEm("1280px"),
			1500: convertToEm("1536px"),
		},
		colors: {
			site: {
				1: "hsl(var(--color-site-1) / <alpha-value>)",
				2: "hsl(var(--color-site-2) / <alpha-value>)",
			},
			text: {
				1: "hsl(var(--color-text-1) / <alpha-value>)",
				2: "hsl(var(--color-text-2) / <alpha-value>)",
				3: "hsl(var(--color-text-3) / <alpha-value>)",
			},
			accent: "hsl(var(--color-accent) / <alpha-value>)",
			border: "hsl(var(--color-border) / <alpha-value>)",
			shadow: "hsl(var(--color-border))",
		},
		/**
		 * Font sizes generated by Utopia - fluid responsive design
		 * https://utopia.fyi/type/calculator?c=640,16,1.2,1536,20,1.2,3,2,&s=0.75|0.5|0.25,1.5|2|3|4|6,s-l&g=s,l,xl,12
		 */
		fontSize: {
			// 11.11px → 13.89px
			0: "clamp(0.6944rem, 0.5703rem + 0.3103vw, 0.8681rem)",
			// 13.33px → 16.67px
			1: "clamp(0.8331rem, 0.684rem + 0.3728vw, 1.0419rem)",
			// 16.00px → 20.00px
			2: "clamp(1rem, 0.8214rem + 0.4464vw, 1.25rem)",
			// 19.20px → 24.00px
			3: "clamp(1.2rem, 0.9857rem + 0.5357vw, 1.5rem)",
			// 23.04px → 28.80px
			4: "clamp(1.44rem, 1.1829rem + 0.6429vw, 1.8rem)",
			// 27.65px → 34.56px
			5: "clamp(1.7281rem, 1.4196rem + 0.7712vw, 2.16rem)",
		},
		/**
		 * Spacing generated by Utopia - fluid responsive design
		 * https://utopia.fyi/space/calculator?c=640,16,1.2,1536,20,1.2,3,2,&s=0.75|0.5|0.25,1.5|2|3|4|6,&g=s,l,xl,12
		 */
		spacing: {
			// 4px → 5px
			0: "clamp(0.25rem, 0.2054rem + 0.1116vw, 0.3125rem)",
			// 8px → 10px
			1: "clamp(0.5rem, 0.4107rem + 0.2232vw, 0.625rem)",
			// 12px → 15px
			2: "clamp(0.75rem, 0.6161rem + 0.3348vw, 0.9375rem)",
			// 16px → 20px
			3: "clamp(1rem, 0.8214rem + 0.4464vw, 1.25rem)",
			// 24px → 30px
			4: "clamp(1.5rem, 1.2321rem + 0.6696vw, 1.875rem)",
			// 32px → 40px
			5: "clamp(2rem, 1.6429rem + 0.8929vw, 2.5rem)",
			// 48px → 60px
			6: "clamp(3rem, 2.4643rem + 1.3393vw, 3.75rem)",
			// 64px → 80px
			7: "clamp(4rem, 3.2857rem + 1.7857vw, 5rem)",
			// 96px → 120px
			8: "clamp(6rem, 4.9286rem + 2.6786vw, 7.5rem)",
		},
	},
	plugins: [],
};
