import type { TProjects } from "$types";

const projects: TProjects = [
	{
		name: "Ik doe mee - AGII",
		date: "2023",
		company: "Little Miss Robot",
		image: "/images/placeholder.jpg",
		role: "Front-end developer",
		link: "https://www.ikdoemee.be/en",
		technologies: [
			"Next",
			"React",
			"Headless Craft CMS",
			"ACM/IDM",
			"Turborepo",
			"Radix UI",
			"Tailwind",
		],
	},
	{
		name: "Hylas",
		date: "2023",
		company: "Little Miss Robot",
		image: "/images/placeholder.jpg",
		role: "Front-end developer",
		link: "https://hylasprovincieantwerpen.be/",
		technologies: [
			"Next",
			"React",
			"Headless Craft CMS",
			"Turborepo",
			"Headless UI",
			"Tailwind",
		],
	},
	{
		name: "Hylas - labo",
		date: "2023",
		company: "Little Miss Robot",
		image: "/images/placeholder.jpg",
		role: "Front-end developer",
		link: "https://labo.hylasprovincieantwerpen.be/",
		technologies: [
			"Next",
			"React",
			"Headless Craft CMS",
			"Three.js",
			"Turborepo",
			"Radix UI",
			"Tailwind",
		],
	},
	{
		name: "Hylas - admin",
		date: "2023",
		company: "Little Miss Robot",
		image: "/images/placeholder.jpg",
		role: "Front-end developer",
		link: "https://mijn.hylasprovincieantwerpen.be/",
		technologies: [
			"Next",
			"React",
			"Headless Craft CMS",
			"Turborepo",
			"Radix UI",
			"Tailwind",
		],
	},
	{
		name: "Thomas More",
		date: "2022",
		company: "Little Miss Robot",
		image: "/images/placeholder.jpg",
		role: "Front-end developer",
		link: "https://thomasmore.be/nl",
		technologies: ["Drupal"],
	},
	{
		name: "Kansstad - VDAB",
		date: "2022",
		company: "Little Miss Robot",
		image: "/images/placeholder.jpg",
		role: "Front-end developer",
		link: "https://kansstad.be",
		technologies: ["Nuxt", "Vue", "Headless Craft CMS", "Phaser"],
	},
	{
		name: "Technotrailer",
		date: "2022",
		company: "Little Miss Robot",
		image: "/images/placeholder.jpg",
		role: "Front-end developer",
		link: "https://technotrailer.be/",
		technologies: ["Craft CMS"],
	},
	{
		name: "Technotrailer - labo",
		date: "2022",
		company: "Little Miss Robot",
		image: "/images/placeholder.jpg",
		role: "Front-end developer",
		link: "https://labo.technotrailer.be/",
		technologies: [
			"Nuxt",
			"Vue",
			"Headless Craft CMS",
			"Three.js",
			"Phaser",
		],
	},
	{
		name: "KMSKA",
		date: "2021",
		company: "Little Miss Robot",
		image: "/images/placeholder.jpg",
		role: "Front-end developer",
		link: "https://play.google.com/store/apps/details?id=be.kmska.app&pli=1",
		technologies: ["Ionic", "Capacitor", "Vue", "Headless Craft CMS"],
	},
	{
		name: "Apvine",
		date: "2021",
		company: "Little Miss Robot",
		image: "/images/placeholder.jpg",
		role: "Front-end developer",
		link: "https://apvine.com/",
		technologies: ["Craft CMS"],
	},
	{
		name: "Edward & the Ghost - An interactive Story",
		date: "2021",
		company: "Little Miss Robot",
		image: "/images/placeholder.jpg",
		role: "Front-end developer",
		link: "https://edwardandtheghost.com/",
		technologies: ["Nuxt", "Vue", "Pixi"],
	},
	{
		name: "Teamleader - 2020 editie",
		date: "2020",
		company: "Little Miss Robot",
		image: "/images/placeholder.jpg",
		role: "Front-end developer",
		link: "https://www.teamleader.eu/nl-be",
		technologies: ["Craft CMS"],
	},
	{
		name: "Hack The Future",
		date: "2019",
		company: "Little Miss Robot",
		image: "/images/placeholder.jpg",
		role: "Front-end developer",
		link: "https://www.hackthefuture.be/home",
		technologies: ["Craft CMS", "Canvas API"],
	},
	{
		name: "Hoog water zonder kater",
		date: "2019",
		company: "Little Miss Robot",
		image: "/images/placeholder.jpg",
		role: "Front-end developer",
		link: "http://hwzk.integraalwaterbeleid.be/",
		technologies: ["Nuxt", "Vue", "Canvas API"],
	},
	{
		name: "NIBC",
		date: "2019",
		company: "Little Miss Robot",
		image: "/images/placeholder.jpg",
		role: "Front-end developer",
		link: "https://www.nibc.be/nl/",
		technologies: [".NET"],
	},
	{
		name: "Cevora",
		date: "2019",
		company: "Little Miss Robot",
		image: "/images/placeholder.jpg",
		role: "Front-end developer",
		link: "https://www.cevora.be/nl/",
		technologies: ["Next", "React"],
	},
	{
		name: "Recycle app",
		date: "2019",
		company: "Little Miss Robot",
		image: "/images/placeholder.jpg",
		role: "Front-end developer",
		link: "https://play.google.com/store/apps/details?id=mobi.inthepocket.fostplus.recyclage&hl=nl&gl=US",
		technologies: ["React Native"],
	},
	{
		name: "GROM - Il gelato come una volta",
		date: "2019",
		company: "Little Miss Robot",
		image: "/images/placeholder.jpg",
		role: "Front-end developer",
		link: "https://grom.leapforward.be/",
		technologies: ["React", "Three.js"],
	},
	{
		name: "Bebat - Villa pila",
		date: "2018",
		company: "Little Miss Robot",
		image: "/images/placeholder.jpg",
		role: "Front-end developer",
		link: "https://www.villapila.be/nl",
		technologies: ["React", "Pixi"],
	},
	{
		name: "Zedelgem",
		date: "2018",
		company: "Little Miss Robot",
		image: "/images/placeholder.jpg",
		role: "Front-end developer",
		link: "https://www.zedelgem.be/",
		technologies: ["Drupal"],
	},
	{
		name: "Woningkwaliteit",
		date: "2018",
		company: "Little Miss Robot",
		image: "/images/placeholder.jpg",
		role: "Front-end developer",
		link: "https://woningpas.vlaanderen.be/",
		technologies: [],
	},
	{
		name: "Woningpas",
		date: "2018",
		company: "Little Miss Robot",
		image: "/images/placeholder.jpg",
		role: "Front-end developer",
		link: "https://woningpas.vlaanderen.be/web/woningkwaliteit/overzicht",
		technologies: [],
	},
];

export default projects;
